truncate table t6_tarifas_aprobaciones
truncate table t6_tarifas_atributos
truncate table t6_tarifas_listas_lista
truncate table t6_tarifas_lista
truncate table t6_tarifas_listas_valores_atributos
truncate table t6_tarifas_maestras_relacion_tarifas
truncate table t6_tarifas_descuentos

truncate table t6_tarifas_prefactura_descunetos_proveedor
truncate table t6_tarifas_proveedor_prefactura
truncate table t6_tarifas_proveedor_prefactura_detalle
truncate table t6_tarifas_prefactura_proyectos
truncate table t6_tarifas_maestras_relacion_tarifas
truncate table t6_tarifas_maestras_valores_descriptores
truncate table t6_tarifas_maestras_categoria
truncate table t6_tarifas_maestras_descriptores
