<? 

	include("../../librerias/lib/@include.php");
	query_db("insert into t_version_2_indi_1(t1_tipo_proceso_id,
											fecha_creacion,
											id_us_profesional_asignado,
											congelado,
											t1_area_id,
											tiempos_estandar,
											de_historico,
											estado,
											tipo_proceso,
											profesional,
											t2_nivel_servicio_id,
											nivel_aprobacion,
											id_item,
											t1_trm_id,
											area,
											id_vp,
											vicepresidente,
											fecha
											)
									SELECT *, getdate() from
									(select * from version_2_indi_1
									except 
									select t1_tipo_proceso_id,
									fecha_creacion,
									id_us_profesional_asignado,
									congelado,
									t1_area_id,
									tiempos_estandar,
									de_historico,
									estado,
									tipo_proceso,
									profesional,
									t2_nivel_servicio_id,
									nivel_aprobacion,
									id_item,
									t1_trm_id,
									area,
									id_vp,
									vicepresidente from t_version_2_indi_1) AS a");
									
	query_db("insert into t_version_2_indi_estado_procesos(t1_tipo_proceso_id,
															estado,
															fecha_creacion,
															id_us_profesional_asignado,
															tiempos_estandar,
															congelado,
															de_historico,
															fecha_reprograma_fin,
															fecha_finalizacion,
															estado_atrazado_atiempo,
															nivel_aprobacion,
															t2_nivel_servicio_actividad_id,
															actividad,
															t2_nivel_servicio_encargado_id,
															encargado,
															t1_area_id,
															solicitud_rechazada,
															solicitud_desierta,
															id_item,
															fecha
															)
															SELECT *, getdate() from
															(select * from version_2_indi_estado_procesos
															except 
															select t1_tipo_proceso_id,
															estado,
															fecha_creacion,
															id_us_profesional_asignado,
															tiempos_estandar,
															congelado,
															de_historico,
															fecha_reprograma_fin,
															fecha_finalizacion,
															estado_atrazado_atiempo,
															nivel_aprobacion,
															t2_nivel_servicio_actividad_id,
															actividad,
															t2_nivel_servicio_encargado_id,
															encargado,
															t1_area_id,
															solicitud_rechazada,
															solicitud_desierta,
															id_item from t_version_2_indi_estado_procesos) AS a");
															
	query_db("insert into t_version_2_indi_nivel_aprobacion_max_aprobacion(id_item,
																			max_id_nivel_aprobacion,
																			t1_tipo_proceso_id,
																			id_us_profesional_asignado,
																			estado,
																			congelado,
																			tiempos_esandar,
																			de_historico,
																			fecha_creacion,
																			t1_area_id,
																			fecha
																			)
																			SELECT *, getdate() from
																			(select * from version_2_indi_nivel_aprobacion_max_aprobacion
																			except 
																			select id_item,
																			max_id_nivel_aprobacion,
																			t1_tipo_proceso_id,
																			id_us_profesional_asignado,
																			estado,
																			congelado,
																			tiempos_esandar,
																			de_historico,
																			fecha_creacion,
																			t1_area_id from t_version_2_indi_nivel_aprobacion_max_aprobacion) AS a");

	query_db("insert into t_version_2_indi_soporte_1(num1,
													num2,
													num3,
													profesional,
													fecha_creacion,
													tipo_proceso,
													area,
													congelado,
													estado_nombre,
													id_us_profesional_asignado,
													t1_tipo_proceso_id,
													t1_area_id,
													tiempos_estandar,
													de_historico,
													estado,
													nivel_aprobacion_nom,
													nivel_aprobacion,
													id_item,
													t2_nivel_servicio_id,
													solicitud_rechazada,
													solicitud_desierta,
													fecha
													)
													SELECT *, getdate() from
													(select * from version_2_indi_soporte_1
													except 
													select num1,
													num2,
													num3,
													profesional,
													fecha_creacion,
													tipo_proceso,
													area,
													congelado,
													estado_nombre,
													id_us_profesional_asignado,
													t1_tipo_proceso_id,
													t1_area_id,
													tiempos_estandar,
													de_historico,
													estado,
													nivel_aprobacion_nom,
													nivel_aprobacion,
													id_item,
													t2_nivel_servicio_id,
													solicitud_rechazada,
													solicitud_desierta from t_version_2_indi_soporte_1) AS a");		

	query_db("insert into t_version_2_indi_soporte_2(num1,
													num2,
													num3,
													profesional,
													fecha_creacion,
													tipo_proceso,
													area,
													congelado,
													estado_nombre,
													id_us_profesional_asignado,
													t1_tipo_proceso_id,
													t1_area_id,
													tiempos_estandar,
													de_historico,
													estado,
													nivel_aprobacion_nom,
													nivel_aprobacion,
													fecha_reprograma_fin,
													fecha_finalizacion,
													estado_atrazado_atiempo,
													id_item,
													t2_nivel_servicio_id,
													solicitud_rechazada,
													solicitud_desierta,
													fecha
													)
													SELECT *, getdate() from
													(select * from version_2_indi_soporte_2
													except 
													select num1,
													num2,
													num3,
													profesional,
													fecha_creacion,
													tipo_proceso,
													area,
													congelado,
													estado_nombre,
													id_us_profesional_asignado,
													t1_tipo_proceso_id,
													t1_area_id,
													tiempos_estandar,
													de_historico,
													estado,
													nivel_aprobacion_nom,
													nivel_aprobacion,
													fecha_reprograma_fin,
													fecha_finalizacion,
													estado_atrazado_atiempo,
													id_item,
													t2_nivel_servicio_id,
													solicitud_rechazada,
													solicitud_desierta from t_version_2_indi_soporte_2) AS a");
													
	query_db("insert into t_version_2_indi_soporte_3(num1,
													num2,
													num3,
													profesional,
													fecha_creacion,
													tipo_proceso,
													area,
													congelado,
													estado_nombre,
													id_us_profesional_asignado,
													t1_tipo_proceso_id,
													t1_area_id,
													tiempos_estandar,
													de_historico,
													estado,
													nivel_aprobacion_nom,
													nivel_aprobacion,
													fecha_reprograma_fin,
													fecha_finalizacion,
													estado_atrazado_atiempo,
													id_item,
													nombre,
													Expr1,	
													t2_nivel_servicio_actividad_id,
													tiempo,
													dias_reales,
													solicitud_rechazada,
													solicitud_desierta,
													t2_nivel_servicio_encargado_id,
													fecha
													)
													SELECT *, getdate() from
													(select * from version_2_indi_soporte_3
													except 
													select num1,
													num2,
													num3,
													profesional,
													fecha_creacion,
													tipo_proceso,
													area,
													congelado,
													estado_nombre,
													id_us_profesional_asignado,
													t1_tipo_proceso_id,
													t1_area_id,
													tiempos_estandar,
													de_historico,
													estado,
													nivel_aprobacion_nom,
													nivel_aprobacion,
													fecha_reprograma_fin,
													fecha_finalizacion,
													estado_atrazado_atiempo,
													id_item,
													nombre,
													Expr1,	
													t2_nivel_servicio_actividad_id,
													tiempo,
													dias_reales,
													solicitud_rechazada,
													solicitud_desierta,
													t2_nivel_servicio_encargado_id from t_version_2_indi_soporte_3) AS a");
?>
<script>
function CloseWin(){
window.open('','_parent','');
window.close(); 
}
CloseWin()
</script>